export const diseaseData: Record<string, {
  image: string;
  description: string;
  prevention: string[];
  treatment: string[];
}> = {
  "Apple___Apple_scab": {
    image: "/img/Apple___Apple_scab.jpg",
    description: "A fungal disease causing dark, scabby spots on apple leaves and fruits.",
    prevention: [
      "Choose resistant apple varieties.",
      "Prune trees for better air circulation.",
      "Avoid overhead watering.",
      "Rake and destroy fallen leaves.",
      "Maintain balanced fertilization.",
    ],
    treatment: [
      "Apply fungicides during early spring.",
      "Use sulfur sprays before bud break.",
      "Remove infected fruits promptly.",
      "Rotate fungicides to prevent resistance.",
      "Monitor regularly for early detection.",
    ],
  },
  "Apple___Black_rot": {
    image: "/img/Apple___Black_rot.jpg",
    description: "A fungal disease that causes leaf spots, fruit rot, and cankers on apple trees.",
    prevention: [
      "Prune and remove dead or diseased branches.",
      "Avoid wounding apple trees during pruning.",
      "Rake and destroy fallen leaves and mummified fruit.",
      "Promote good air circulation in orchards.",
      "Plant in well-drained soil.",
    ],
    treatment: [
      "Apply fungicides containing captan or copper.",
      "Remove and burn infected fruits.",
      "Cut and destroy cankered branches.",
      "Disinfect tools after pruning diseased trees.",
      "Monitor regularly and apply fungicide sprays in wet seasons.",
    ],
  },
  "Apple___Cedar_apple_rust": {
    image: "/img/Apple___Cedar_apple_rust.jpg",
    description: "A fungal disease that alternates between apple and cedar trees, causing orange leaf spots.",
    prevention: [
      "Plant apple varieties resistant to rust.",
      "Avoid planting apples near juniper or cedar trees.",
      "Prune branches to improve airflow.",
      "Remove nearby cedar galls.",
      "Monitor orchard during spring rains.",
    ],
    treatment: [
      "Apply fungicides at bud break.",
      "Spray protective fungicides every 7–10 days during spring.",
      "Remove and destroy cedar galls before spore release.",
      "Use systemic fungicides for severe infections.",
      "Rotate fungicides to reduce resistance buildup.",
    ],
  },
  "Apple___healthy": {
    image: "/img/Apple___healthy.jpg",
    description: "The tree is thriving with shiny, green leaves and healthy fruits.",
    prevention: [
      "Water at the base, not on leaves.",
      "Use disease-resistant varieties.",
      "Ensure proper orchard spacing.",
      "Keep pruning tools sanitized.",
      "Mulch around the base to reduce weeds.",
    ],
    treatment: [
      "The plant is healthy; no treatment is needed.",
    ],
  },
  "Background_without_leaves": {
    image: "/img/Background_without_leaves.jpg",
    description: "No plant disease present, just background.",
    prevention: [
      "Maintain healthy soil practices.",
      "Avoid excess standing water.",
      "Rotate crops when planting again.",
      "Sanitize field equipment.",
      "Clear plant debris after harvest.",
    ],
    treatment: [
      "The plant is healthy; no treatment is needed.",
    ],
  },
  "Blueberry___healthy": {
    image: "/img/Blueberry___healthy.jpg",
    description: "The bush is vibrant, with firm, plump berries.",
    prevention: [
      "Maintain soil pH at 4.5–5.5.",
      "Water evenly without wetting foliage.",
      "Remove old canes to increase airflow.",
      "Mulch to prevent soil splash.",
      "Choose disease-resistant cultivars.",
    ],
    treatment: [
      "The plant is healthy; no treatment is needed.",
    ],
  },
  "Cherry___Powdery_mildew": {
    image: "/img/Cherry___Powdery_mildew.jpg",
    description: "A fungal disease causing white, powdery growth on cherry leaves and shoots.",
    prevention: [
      "Avoid overhead irrigation.",
      "Plant in full sun locations.",
      "Space trees for good air flow.",
      "Select mildew-resistant varieties.",
      "Prune infected shoots annually.",
    ],
    treatment: [
      "Apply sulfur fungicides early in infection.",
      "Use horticultural oils to control fungi.",
      "Spray potassium bicarbonate solutions.",
      "Remove severely affected leaves.",
      "Apply fungicides every 10–14 days in wet weather.",
    ],
  },
  "Cherry___healthy": {
    image: "/img/Cherry___healthy.jpg",
    description: "The plant is flourishing with glossy green leaves and firm fruits.",
    prevention: [
      "Water at ground level.",
      "Keep pruning tools disinfected.",
      "Select resistant cherry varieties.",
      "Improve soil drainage.",
      "Apply balanced fertilizers.",
    ],
    treatment: [
      "The plant is healthy; no treatment is needed.",
    ],
  },
  "Corn___Cercospora_leaf_spot Gray_leaf_spot": {
    image: "/img/Corn___Cercospora_leaf_spot Gray_leaf_spot.jpg",
    description: "A fungal leaf spot disease causing gray to tan rectangular lesions on corn leaves.",
    prevention: [
      "Plant resistant hybrid corn varieties.",
      "Rotate crops to non-host plants.",
      "Avoid dense planting to reduce humidity.",
      "Plow crop residue under soil.",
      "Water early to allow leaves to dry quickly.",
    ],
    treatment: [
      "Apply fungicides at tasseling stage.",
      "Rotate fungicides to prevent resistance.",
      "Scout fields regularly during humid seasons.",
      "Destroy heavily infected residue after harvest.",
      "Use foliar fungicides when disease pressure is high.",
    ],
  },
  "Corn___Common_rust": {
    image: "/img/Corn___Common_rust.jpg",
    description: "A fungal disease producing reddish-brown pustules on corn leaves.",
    prevention: [
      "Plant resistant corn hybrids.",
      "Practice crop rotation.",
      "Avoid planting in areas with excess humidity.",
      "Maintain large field spacing for airflow.",
      "Scout during mid-season for early detection.",
    ],
    treatment: [
      "Apply preventive fungicide sprays.",
      "Rotate fungicides with different modes of action.",
      "Remove infected crop debris after harvest.",
      "Use foliar sprays when disease severity is high.",
      "Enhance plant nutrition to strengthen resistance.",
    ],
  },
  "Corn___Northern_Leaf_Blight": {
    image: "/img/Corn___Northern_Leaf_Blight.jpg",
    description: "A fungal infection that causes long, grayish-green lesions on corn leaves.",
    prevention: [
      "Choose resistant corn varieties.",
      "Rotate crops with non-corn species.",
      "Avoid leaving residues on the soil surface.",
      "Plant in rows with proper spacing.",
      "Promote early-season vigor with fertilization.",
    ],
    treatment: [
      "Apply fungicides at first appearance of symptoms.",
      "Remove infected residue post-harvest.",
      "Rotate fungicide classes.",
      "Use aerial sprays during widespread outbreaks.",
      "Implement early planting to escape peak fungal season.",
    ],
  },
  "Corn___healthy": {
    image: "/img/Corn___healthy.jpg",
    description: "The corn is tall, lush, and vigorous with green leaves.",
    prevention: [
      "Rotate crops to prevent soilborne pathogens.",
      "Use resistant varieties.",
      "Irrigate early to let leaves dry quickly.",
      "Improve field drainage.",
      "Monitor regularly for pests and fungi.",
    ],
    treatment: [
      "The plant is healthy; no treatment is needed.",
    ],
  },
  "Grape___Black_rot": {
    image: "/img/Grape___Black_rot.jpg",
    description: "A fungal disease that causes circular brown leaf spots and shriveled \"mummy\" fruits.",
    prevention: [
      "Plant resistant grape cultivars.",
      "Prune vines to allow good air circulation.",
      "Remove fallen leaves and infected fruits.",
      "Train vines to trellises for better airflow.",
      "Rotate crops and avoid planting in poorly drained soil.",
    ],
    treatment: [
      "Apply fungicides early in the season.",
      "Use protective sprays at bloom and fruit set.",
      "Remove overwintered mummified berries.",
      "Destroy infected plant debris.",
      "Rotate fungicide types to prevent resistance.",
    ],
  },
  "Grape___Esca_(Black_Measles)": {
    image: "/img/Grape___Esca_(Black_Measles).jpg",
    description: "A fungal trunk disease causing dark leaf spots, vine decline, and berry shriveling.",
    prevention: [
      "Use certified disease-free planting material.",
      "Prune during dry weather to reduce infection risk.",
      "Avoid large pruning wounds.",
      "Disinfect pruning shears regularly.",
      "Improve vineyard airflow and drainage.",
    ],
    treatment: [
      "Remove and destroy infected vines.",
      "Seal large pruning wounds with fungicidal pastes.",
      "Apply systemic fungicides against trunk pathogens.",
      "Avoid mechanical injuries to the vines.",
      "Replant vineyards with tolerant varieties.",
    ],
  },
  "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": {
    image: "/img/Grape___Leaf_blight_(Isariopsis_Leaf_Spot).jpg",
    description: "A fungal disease causing angular necrotic spots on grape leaves, reducing photosynthesis.",
    prevention: [
      "Practice proper canopy management for sunlight penetration.",
      "Choose resistant grape varieties.",
      "Avoid overhead irrigation.",
      "Remove fallen debris after harvest.",
      "Space vines properly for airflow.",
    ],
    treatment: [
      "Spray fungicides during the growing season.",
      "Apply copper-based protectant fungicides.",
      "Rotate fungicide classes to prevent resistance.",
      "Destroy infected leaves promptly.",
      "Use systemic fungicides in severe cases.",
    ],
  },
  "Grape___healthy": {
    image: "/img/Grape___healthy.jpg",
    description: "The grapevine is thriving with lush leaves and healthy grape clusters.",
    prevention: [
      "Prune vines regularly for good airflow.",
      "Irrigate at the soil level, not on foliage.",
      "Select resistant grape varieties.",
      "Apply organic mulch to reduce soil splash.",
      "Keep vineyard free of weeds and debris.",
    ],
    treatment: [
      "The plant is healthy; no treatment is needed.",
    ],
  },
  "Orange___Haunglongbing_(Citrus_greening)": {
    image: "/img/Orange___Haunglongbing_(Citrus_greening).jpg",
    description: "A bacterial disease spread by citrus psyllids, causing yellow shoots, misshapen fruit, and tree decline.",
    prevention: [
      "Use disease-free nursery stock.",
      "Remove infected trees promptly.",
      "Control psyllid populations with insecticides.",
      "Plant citrus varieties with some tolerance.",
      "Monitor orchards regularly for yellow shoot symptoms.",
    ],
    treatment: [
      "Apply systemic insecticides to kill psyllids.",
      "Use reflective mulches to deter psyllid landing.",
      "Provide balanced fertilization to reduce stress.",
      "Apply antibiotics (where legally permitted).",
      "Implement area-wide management with neighboring growers.",
    ],
  },
  "Peach___Bacterial_spot": {
    image: "/img/Peach___Bacterial_spot.jpg",
    description: "A bacterial disease that creates dark, water-soaked spots on peach leaves and fruit.",
    prevention: [
      "Choose resistant peach cultivars.",
      "Prune trees to increase airflow.",
      "Avoid overhead irrigation.",
      "Apply copper sprays before bud break.",
      "Destroy infected plant debris.",
    ],
    treatment: [
      "Apply copper-based bactericides.",
      "Spray oxytetracycline during bloom.",
      "Remove and destroy infected fruits.",
      "Practice orchard sanitation by burning debris.",
      "Rotate with resistant rootstocks when replanting.",
    ],
  },
  "Peach___healthy": {
    image: "/img/Peach___healthy.jpg",
    description: "The tree is flourishing with glossy green leaves and vibrant growth.",
    prevention: [
      "Water around the roots, not on foliage.",
      "Prune annually for shape and airflow.",
      "Choose resistant peach varieties.",
      "Fertilize with balanced nutrients.",
      "Maintain orchard floor free from infected debris.",
    ],
    treatment: [
      "The plant is healthy; no treatment is needed.",
    ],
  },
  "Pepper,_bell___Bacterial_spot": {
    image: "/img/Pepper,_bell___Bacterial_spot.jpg",
    description: "A bacterial disease that produces dark, wet spots on leaves and fruits of peppers.",
    prevention: [
      "Plant certified disease-free seeds.",
      "Avoid working with wet plants.",
      "Do crop rotation with non-host plants.",
      "Mulch to prevent soil splash.",
      "Remove volunteers and weeds near peppers.",
    ],
    treatment: [
      "Apply copper-based sprays regularly.",
      "Use bactericides in early crop stages.",
      "Destroy severely infected plants.",
      "Avoid saving seeds from diseased crops.",
      "Rotate with at least 2–3 years between pepper/tomato crops.",
    ],
  },
  "Pepper,_bell___healthy": {
    image: "/img/Pepper,_bell___healthy.jpg",
    description: "The pepper plant is strong with healthy green foliage and glossy fruits.",
    prevention: [
      "Use resistant pepper varieties.",
      "Water at soil level, not leaves.",
      "Encourage airflow with proper spacing.",
      "Rotate crops yearly to avoid soilborne pathogens.",
      "Keep fields free of weeds and fallen debris.",
    ],
    treatment: [
      "The plant is healthy; no treatment is needed.",
    ],
  },
  "Potato___Early_blight": {
    image: "/img/Potato___Early_blight.jpg",
    description: "A fungal disease causing concentric brown spots on leaves, leading to premature defoliation.",
    prevention: [
      "Plant certified disease-free seed potatoes.",
      "Rotate with non-host crops.",
      "Avoid overhead irrigation to reduce humidity.",
      "Destroy potato residue after harvest.",
      "Space rows to ensure airflow.",
    ],
    treatment: [
      "Apply fungicides at first signs of infection.",
      "Rotate fungicides for resistance management.",
      "Remove infected leaves when possible.",
      "Ensure good nutrition to strengthen resistance.",
      "Use resistant potato varieties.",
    ],
  },
  "Potato___Late_blight": {
    image: "/img/Potato___Late_blight.jpg",
    description: "A devastating fungal disease causing large dark leaf spots and rapid rot of potato tubers.",
    prevention: [
      "Plant certified disease-free seed potatoes.",
      "Avoid overhead watering to reduce leaf wetness.",
      "Destroy volunteer potatoes in the field.",
      "Rotate with non-solanaceous crops for several years.",
      "Choose resistant potato varieties.",
    ],
    treatment: [
      "Apply fungicides preventively in wet weather.",
      "Remove and destroy infected plants immediately.",
      "Use systemic fungicides like metalaxyl in outbreaks.",
      "Hill soil around tubers to protect them.",
      "Rotate fungicides to avoid resistance.",
    ],
  },
  "Potato___healthy": {
    image: "/img/Potato___healthy.jpg",
    description: "The potato crop is thriving with lush, green foliage and strong tubers.",
    prevention: [
      "Use certified seed potatoes.",
      "Rotate crops yearly to reduce soil diseases.",
      "Keep soil well-drained and loose.",
      "Avoid watering during the evening.",
      "Keep fields free from weeds and debris.",
    ],
    treatment: [
      "The plant is healthy; no treatment is needed.",
    ],
  },
  "Raspberry___healthy": {
    image: "/img/Raspberry___healthy.jpg",
    description: "The raspberry bush is full of vigor with bright leaves and healthy berries.",
    prevention: [
      "Plant in well-drained soil.",
      "Avoid overhead irrigation.",
      "Space plants for good airflow.",
      "Prune back old canes after harvest.",
      "Keep rows weed-free.",
    ],
    treatment: [
      "The plant is healthy; no treatment is needed.",
    ],
  },
  "Soybean___healthy": {
    image: "/img/Soybean___healthy.jpg",
    description: "The soybean field is lush and vibrant with strong green foliage.",
    prevention: [
      "Rotate crops with corn or small grains.",
      "Use disease-resistant soybean varieties.",
      "Seed at the right depth in well-drained soil.",
      "Scout fields regularly for pests.",
      "Ensure balanced soil fertility.",
    ],
    treatment: [
      "The plant is healthy; no treatment is needed.",
    ],
  },
  "Squash___Powdery_mildew": {
    image: "/img/Squash___Powdery_mildew.jpg",
    description: "A fungal disease forming white, powdery spots on squash leaves, reducing yield.",
    prevention: [
      "Plant resistant squash varieties.",
      "Water at soil level, not leaves.",
      "Space plants to improve airflow.",
      "Avoid excess nitrogen fertilization.",
      "Remove infected leaves promptly.",
    ],
    treatment: [
      "Apply sulfur or neem oil sprays.",
      "Use potassium bicarbonate sprays for control.",
      "Rotate fungicides during the season.",
      "Introduce resistant squash cultivars.",
      "Destroy infected plant residues.",
    ],
  },
  "Strawberry___Leaf_scorch": {
    image: "/img/Strawberry___Leaf_scorch.jpg",
    description: "A fungal disease causing small dark spots and scorched margins on strawberry leaves.",
    prevention: [
      "Plant resistant strawberry cultivars.",
      "Use drip irrigation to avoid leaf wetness.",
      "Remove infected leaves after harvest.",
      "Space plants for good air circulation.",
      "Avoid working with wet plants.",
    ],
    treatment: [
      "Apply fungicides during wet seasons.",
      "Destroy old leaves in summer renovation.",
      "Spray protectant fungicides before fruiting.",
      "Remove weeds around beds.",
      "Rotate fields after several years.",
    ],
  },
  "Strawberry___healthy": {
    image: "/img/Strawberry___healthy.jpg",
    description: "The strawberry bed is green and full, with strong foliage and healthy fruits.",
    prevention: [
      "Plant disease-free certified runners.",
      "Provide well-draining soil.",
      "Water at ground level, not on leaves.",
      "Renovate old beds annually.",
      "Keep weeds and debris cleared.",
    ],
    treatment: [
      "The plant is healthy; no treatment is needed.",
    ],
  },
  "Tomato___Bacterial_spot": {
    image: "/img/Tomato___Bacterial_spot.jpg",
    description: "A bacterial disease causing dark, greasy leaf and fruit spots that reduce yield.",
    prevention: [
      "Use certified disease-free seed.",
      "Avoid working in fields when wet.",
      "Rotate crops with non-solanaceous crops.",
      "Mulch to reduce soil splash.",
      "Select resistant tomato varieties when possible.",
    ],
    treatment: [
      "Apply copper-based bactericides regularly.",
      "Destroy infected residue after harvest.",
      "Avoid saving seeds from diseased plants.",
      "Spray biological agents like Bacillus subtilis.",
      "Remove severely infected plants.",
    ],
  },
  "Tomato___Early_blight": {
    image: "/img/Tomato___Early_blight.jpeg",
    description: "A fungal disease causing concentric brown leaf spots and premature defoliation.",
    prevention: [
      "Plant resistant tomato varieties.",
      "Rotate crops with cereals or legumes.",
      "Water early in the day to dry foliage.",
      "Stake or cage plants to keep leaves dry.",
      "Remove diseased leaves promptly.",
    ],
    treatment: [
      "Spray chlorothalonil or mancozeb fungicides.",
      "Rotate systemic fungicides for resistance.",
      "Destroy infected debris after harvest.",
      "Apply bio-fungicides like Trichoderma.",
      "Mulch to prevent soil splash.",
    ],
  },
  "Tomato___Late_blight": {
    image: "/img/Tomato___Late_blight.jpg",
    description: "A destructive fungal disease causing large brown lesions on leaves and fruits with white fuzz.",
    prevention: [
      "Use blight-resistant tomato varieties.",
      "Avoid prolonged leaf wetness and dense planting.",
      "Rotate crops with non-solanaceous plants.",
      "Eliminate volunteer tomatoes and potatoes nearby.",
      "Scout frequently in wet weather.",
    ],
    treatment: [
      "Apply fungicides such as mancozeb or copper.",
      "Use systemic fungicides during disease pressure.",
      "Remove infected leaves quickly.",
      "Destroy affected plants to protect others.",
      "Rotate fungicidal sprays.",
    ],
  },
  "Tomato___Leaf_Mold": {
    image: "/img/Tomato___Leaf_Mold.jpg",
    description: "A fungal disease causing velvety olive-green mold on the underside of tomato leaves.",
    prevention: [
      "Grow resistant tomato varieties.",
      "Prune to improve airflow inside canopy.",
      "Avoid overhead watering.",
      "Disinfect greenhouses between seasons.",
      "Reduce humidity with ventilation.",
    ],
    treatment: [
      "Spray fungicides such as chlorothalonil.",
      "Apply sulfur during initial infection.",
      "Remove and destroy infected foliage.",
      "Ventilate greenhouses effectively.",
      "Rotate fungicides.",
    ],
  },
  "Tomato___Septoria_leaf_spot": {
    image: "/img/Tomato___Septoria_leaf_spot.jpg",
    description: "A fungal disease causing small, water-soaked spots that later develop tan centers.",
    prevention: [
      "Rotate crops with non-solanaceous plants.",
      "Avoid overhead irrigation.",
      "Space plants for airflow.",
      "Mulch soil to reduce splashing.",
      "Choose resistant varieties.",
    ],
    treatment: [
      "Apply fungicides like chlorothalonil.",
      "Destroy plant debris post-harvest.",
      "Remove lower infected leaves.",
      "Use biological controls like Trichoderma.",
      "Spray fungicides weekly during outbreaks.",
    ],
  },
  "Tomato___Spider_mites Two-spotted_spider_mite": {
    image: "/img/Tomato___Spider_mites Two-spotted_spider_mite.jpg",
    description: "A pest infestation causing stippling, yellowing, and webbing on tomato leaves.",
    prevention: [
      "Regularly scout the undersides of leaves.",
      "Encourage beneficial predatory mites.",
      "Avoid water stress in plants.",
      "Provide sufficient spacing for healthy growth.",
      "Maintain weed control in and around beds.",
    ],
    treatment: [
      "Apply insecticidal soaps or horticultural oils.",
      "Introduce predatory mites like Phytoseiulus persimilis.",
      "Spray neem oil solutions.",
      "Use miticides for heavy infestations.",
      "Prune and destroy infested leaves.",
    ],
  },
  "Tomato___Target_Spot": {
    image: "/img/Tomato___Target_Spot.jpg",
    description: "A fungal disease creating dark concentric spots on tomato leaves and fruits.",
    prevention: [
      "Plant resistant cultivars when available.",
      "Use drip irrigation instead of sprinklers.",
      "Maintain wide row spacing.",
      "Destroy infected residues.",
      "Scout regularly for early intervention.",
    ],
    treatment: [
      "Apply protectant fungicides early.",
      "Rotate fungicides to prevent resistance.",
      "Remove diseased leaves promptly.",
      "Use copper-based sprays.",
      "Spray systemic fungicides if infection spreads.",
    ],
  },
  "Tomato___Tomato_Yellow_Leaf_Curl_Virus": {
    image: "/img/Tomato___Tomato_Yellow_Leaf_Curl_Virus.jpg",
    description: "A viral disease spread by whiteflies, causing yellowing and curling of tomato leaves.",
    prevention: [
      "Use resistant tomato hybrids.",
      "Control whitefly populations promptly.",
      "Use reflective mulches to repel insects.",
      "Cover young plants with insect netting.",
      "Remove weeds that harbor whiteflies.",
    ],
    treatment: [
      "Rogue infected plants immediately.",
      "Use systemic insecticides against whiteflies.",
      "Apply biocontrols like Encarsia formosa.",
      "Spray neem oil to deter whiteflies.",
      "Implement crop rotation.",
    ],
  },
  "Tomato___Tomato_mosaic_virus": {
    image: "/img/Tomato___Tomato_mosaic_virus.jpg",
    description: "A highly contagious viral disease causing mottling, leaf distortion, and stunted growth.",
    prevention: [
      "Use virus-free certified seeds.",
      "Disinfect hands and tools after handling plants.",
      "Avoid tobacco handling before touching plants.",
      "Remove infected plants immediately.",
      "Rotate with non-host crops.",
    ],
    treatment: [
      "Destroy infected plants entirely.",
      "Disinfect greenhouse tools and surfaces.",
      "Use resistant tomato cultivars.",
      "Control aphids and mechanical vectors.",
      "Practice strict sanitation during transplanting.",
    ],
  },
  "Tomato___healthy": {
    image: "/img/Tomato___healthy.jpg",
    description: "The tomato plant is flourishing with deep green leaves and shiny red fruits.",
    prevention: [
      "Water at soil level, not foliage.",
      "Use resistant hybrid tomato varieties.",
      "Stake plants to keep leaves off soil.",
      "Rotate crops annually.",
      "Remove weeds around tomato beds.",
    ],
    treatment: [
      "The plant is healthy; no treatment is needed.",
    ],
  },
};